import Head from 'next/head';
import Image from 'next/image';

import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Resting Boat Face: Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Willkommen, Bienvenue, Welcome...
          <br />
          to Resting Boat Face
        </h1>
        <h3>
          <em>Ahoy, Ahoy!</em>
        </h3>

        <div className={styles.grid}>
          <p>
            A personal log of learning to sail in 2022+ and buying our first
            boat and the adventures we had and times and places we sailed
          </p>
          <p>
            Follow me on instagram -
            <a href={'https://www.instagram.com/restingboatface/'}>
              @RestingBoatFace
            </a>
          </p>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>&copy; RBF 2022</p>
      </footer>
    </div>
  );
}
